
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author reyes.jenneth
 */
public class AddQueue extends javax.swing.JFrame {

    /**
     * Creates new form AddQueue
     */
    static int number = 0;
    public AddQueue() {
        initComponents();
    }

    public static String getId() {
        number += 1;
        String padded = String.format("%06d", number);
        return padded;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderBGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PatientIDTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SubmitQButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RegPatientButton = new javax.swing.JButton();
        jTextFieldFname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MButton = new javax.swing.JRadioButton();
        FButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        ClearField = new javax.swing.JButton();
        SpecComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabelAssignID = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldAddress = new javax.swing.JTextArea();
        jLabelConfirm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 241, 254));

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 40)); // NOI18N
        jLabel1.setText("ADD QUEUE");

        PatientIDTextField.setFont(new java.awt.Font("Proxima Nova Rg", 0, 30)); // NOI18N
        PatientIDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PatientIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientIDTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 25)); // NOI18N
        jLabel2.setText("Patient ID:");

        SubmitQButton.setBackground(new java.awt.Color(0, 177, 106));
        SubmitQButton.setFont(new java.awt.Font("Proxima Nova Rg", 1, 20)); // NOI18N
        SubmitQButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitQButton.setText("SUBMIT");
        SubmitQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitQButtonActionPerformed(evt);
            }
        });

        HomeButton.setBackground(new java.awt.Color(27, 163, 156));
        HomeButton.setFont(new java.awt.Font("Proxima Nova Rg", 1, 20)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton.setText("BACK TO HOME");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 40)); // NOI18N
        jLabel3.setText("NEW PATIENT");

        RegPatientButton.setBackground(new java.awt.Color(0, 177, 106));
        RegPatientButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 20)); // NOI18N
        RegPatientButton.setForeground(new java.awt.Color(255, 255, 255));
        RegPatientButton.setText("REGISTER");
        RegPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegPatientButtonActionPerformed(evt);
            }
        });

        jTextFieldFname.setFont(new java.awt.Font("Proxima Nova Rg", 0, 18)); // NOI18N
        jTextFieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel4.setText("First name:");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel5.setText("Middle name:");

        jTextFieldMname.setFont(new java.awt.Font("Proxima Nova Rg", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel6.setText("Last name:");

        jTextFieldLname.setFont(new java.awt.Font("Proxima Nova Rg", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel7.setText("Gender:");

        MButton.setBackground(new java.awt.Color(228, 241, 254));
        GenderBGroup.add(MButton);
        MButton.setFont(new java.awt.Font("Proxima Nova Rg", 0, 20)); // NOI18N
        MButton.setText("Male");
        MButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MButtonActionPerformed(evt);
            }
        });

        FButton.setBackground(new java.awt.Color(228, 241, 254));
        GenderBGroup.add(FButton);
        FButton.setFont(new java.awt.Font("Proxima Nova Rg", 0, 20)); // NOI18N
        FButton.setText("Female");
        FButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel8.setText("Age:");

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel9.setText("Address:");

        jTextFieldAge.setFont(new java.awt.Font("Proxima Nova Rg", 0, 18)); // NOI18N
        jTextFieldAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ClearField.setBackground(new java.awt.Color(0, 177, 106));
        ClearField.setFont(new java.awt.Font("Proxima Nova Rg", 1, 20)); // NOI18N
        ClearField.setForeground(new java.awt.Color(255, 255, 255));
        ClearField.setText("CLEAR FIELD");
        ClearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFieldActionPerformed(evt);
            }
        });

        SpecComboBox.setFont(new java.awt.Font("Poppins", 0, 22)); // NOI18N
        SpecComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pediatrician", "Opthalmologist", "Dermatologist", "ENT", "Internal Medicine", "Ob-Gyne", "OB Sonologist", "Radio Sonologist", "Surgery", "Urologist" }));
        SpecComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 25)); // NOI18N
        jLabel10.setText("Services:");

        jLabelAssignID.setFont(new java.awt.Font("Proxima Nova Rg", 0, 26)); // NOI18N
        jLabelAssignID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAssignID.setText(" ");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextFieldAddress.setColumns(20);
        jTextFieldAddress.setFont(new java.awt.Font("Proxima Nova Rg", 0, 18)); // NOI18N
        jTextFieldAddress.setRows(5);
        jTextFieldAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabelConfirm.setFont(new java.awt.Font("Proxima Nova Rg", 0, 20)); // NOI18N
        jLabelConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConfirm.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SpecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PatientIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(153, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(SubmitQButton)
                                .addGap(188, 188, 188))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(HomeButton)
                                .addGap(146, 146, 146))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabelConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ClearField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RegPatientButton))
                            .addComponent(jLabelAssignID, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldLname, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                        .addComponent(jTextFieldMname)
                                        .addComponent(jTextFieldFname))
                                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldAge, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(51, 51, 51)
                                        .addComponent(FButton))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel3)))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(SpecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FButton)
                            .addComponent(MButton)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAssignID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabelConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitQButton)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegPatientButton)
                            .addComponent(ClearField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(HomeButton)))
                .addGap(40, 40, 40))
            .addComponent(jSeparator2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatientIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientIDTextFieldActionPerformed

    private void SubmitQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitQButtonActionPerformed
        String pid = PatientIDTextField.getText();
        String query = "SELECT * FROM patients WHERE patient_id = '"+pid+"'";
        String firstname = null,lastname = null, id = null;
        
        try{
            Connection con = MyConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(query);
            
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                firstname = rs.getString("firstname");
                lastname = rs.getString("lastname");
                id = rs.getString("patient_id");
            }
            
            if (pid.equals(id)){
                String service = SpecComboBox.getSelectedItem().toString();
                String addQ = "INSERT INTO queue(patient_id,service) VALUES(?,?)";
                ps = MyConnection.getConnection().prepareStatement(addQ);
                ps.setString(1, pid);
                ps.setString(2, service);
                if(ps.executeUpdate() > 0){
                    PatientIDTextField.setText("");
                    JOptionPane.showMessageDialog(null,firstname+" "+lastname+"\nhas been added to queue");
                }
            } else 
                JOptionPane.showMessageDialog(null,"Patient ID not found!");
            
        }catch (Exception ex){
            System.out.println("Scan_DB Error: " + ex);
        }
               
    }//GEN-LAST:event_SubmitQButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        ReceptionView rv = new ReceptionView();
        rv.setVisible(true);
        rv.pack();
        rv.setLocationRelativeTo(null);
        //rv.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void RegPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegPatientButtonActionPerformed
        String fname = jTextFieldFname.getText();
        String mname = jTextFieldMname.getText();
        String lname = jTextFieldLname.getText();
        String address = jTextFieldAddress.getText();
        int age = Integer.parseInt(jTextFieldAge.getText());
        //LocalDate date = java.time.LocalDate.now();
        String patient_id = getId();
        String gender = null;
        PreparedStatement ps;
        String query = "INSERT INTO patients(patient_id,firstname,midname,lastname,address,gender,age) VALUES (?,?,?,?,?,?,?)";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, patient_id);
            ps.setString(2, fname);
            ps.setString(3, mname);
            ps.setString(4, lname);
            ps.setString(5, address);
            
            if (MButton.isSelected())
                gender = "Male";
            else if (FButton.isSelected())
                gender = "Female";
            ps.setString(6, gender);
            ps.setInt(7, age);
            //ps.setDate(8,date);
            
            if(ps.executeUpdate() > 0)
            {
                jLabelAssignID.setText("PATIENT ID: "+patient_id);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddQueue.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_RegPatientButtonActionPerformed

    private void jTextFieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFnameActionPerformed

    private void FButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FButtonActionPerformed
        
    }//GEN-LAST:event_FButtonActionPerformed

    private void ClearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFieldActionPerformed
        jTextFieldFname.setText("");
        jTextFieldMname.setText("");
        jTextFieldLname.setText("");
        jTextFieldAddress.setText("");
        jTextFieldAge.setText("");
        jLabelAssignID.setText(" ");
        GenderBGroup.clearSelection();
    }//GEN-LAST:event_ClearFieldActionPerformed

    private void SpecComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecComboBoxActionPerformed

    private void MButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MButtonActionPerformed
        
    }//GEN-LAST:event_MButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQueue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearField;
    private javax.swing.JRadioButton FButton;
    private javax.swing.ButtonGroup GenderBGroup;
    private javax.swing.JButton HomeButton;
    private javax.swing.JRadioButton MButton;
    private javax.swing.JTextField PatientIDTextField;
    private javax.swing.JButton RegPatientButton;
    private javax.swing.JComboBox<String> SpecComboBox;
    private javax.swing.JButton SubmitQButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAssignID;
    private javax.swing.JLabel jLabelConfirm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextFieldAddress;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldMname;
    // End of variables declaration//GEN-END:variables
}
