
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author reyes.jenneth
 */
public class flashscreen extends javax.swing.JFrame {

    /**
     * Creates new form flashscreen
     */
    public flashscreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Flashscreen = new javax.swing.JPanel();
        WcLabel = new javax.swing.JLabel();
        KRLabel = new javax.swing.JLabel();
        MedLabel = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        UsersComboBox = new javax.swing.JComboBox<>();
        EnterButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Flashscreen.setBackground(new java.awt.Color(228, 241, 254));

        WcLabel.setFont(new java.awt.Font("Sitka Heading", 0, 34)); // NOI18N
        WcLabel.setText("W E L C O M E   T O");

        KRLabel.setFont(new java.awt.Font("Sitka Small", 0, 44)); // NOI18N
        KRLabel.setText("Konsulta@Resulta");

        MedLabel.setFont(new java.awt.Font("Sitka Text", 0, 26)); // NOI18N
        MedLabel.setText("MEDICAL CLINIC AND LABORATORY");

        LoginLabel.setFont(new java.awt.Font("Sitka Text", 0, 26)); // NOI18N
        LoginLabel.setText("Login as:");

        UsersComboBox.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        UsersComboBox.setMaximumRowCount(4);
        UsersComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reception", "Dermatologist", "ENT", "Internal Medicine", "Opthalmologist", "Ob-gyne", "OB Sonologist", "Pediatrician", "Radio Sonologist", "Surgery", "Urologist" }));
        UsersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersComboBoxActionPerformed(evt);
            }
        });

        EnterButton.setBackground(new java.awt.Color(0, 177, 106));
        EnterButton.setFont(new java.awt.Font("Proxima Nova Rg", 1, 24)); // NOI18N
        EnterButton.setForeground(new java.awt.Color(255, 255, 255));
        EnterButton.setText("ENTER");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(255, 153, 153));
        ExitButton.setFont(new java.awt.Font("Proxima Nova Rg", 1, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("  EXIT  ");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FlashscreenLayout = new javax.swing.GroupLayout(Flashscreen);
        Flashscreen.setLayout(FlashscreenLayout);
        FlashscreenLayout.setHorizontalGroup(
            FlashscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlashscreenLayout.createSequentialGroup()
                .addGroup(FlashscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FlashscreenLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(LoginLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UsersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FlashscreenLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(FlashscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MedLabel)
                            .addGroup(FlashscreenLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(KRLabel))))
                    .addGroup(FlashscreenLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(WcLabel)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(FlashscreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton)
                .addGap(54, 54, 54)
                .addComponent(EnterButton)
                .addGap(225, 225, 225))
        );
        FlashscreenLayout.setVerticalGroup(
            FlashscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlashscreenLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(WcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FlashscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FlashscreenLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(MedLabel))
                    .addComponent(KRLabel))
                .addGap(55, 55, 55)
                .addGroup(FlashscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginLabel)
                    .addComponent(UsersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(FlashscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(EnterButton))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Flashscreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Flashscreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsersComboBoxActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        String user = UsersComboBox.getSelectedItem().toString();
        if (user == "Reception"){
            ReceptionView rv = new ReceptionView();
            rv.setVisible(true);
            rv.pack();
            rv.setLocationRelativeTo(null);
            rv.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        } else {
            DoctorView dv = new DoctorView();
            dv.setVisible(true);
            dv.pack();
            dv.setLocationRelativeTo(null);
            dv.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
        this.dispose();
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        
    }//GEN-LAST:event_ExitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flashscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPanel Flashscreen;
    private javax.swing.JLabel KRLabel;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel MedLabel;
    private javax.swing.JComboBox<String> UsersComboBox;
    private javax.swing.JLabel WcLabel;
    // End of variables declaration//GEN-END:variables
}
